name: Deploy Lambda Function

on:
  push:
    branches: [ main ]
    paths:
      - 'aws/lambda/**'
      - '.github/workflows/deploy-lambda.yml'

env:
  LAMBDA_FUNCTION: AIponATimeCustomerCare
  LAMBDA_RUNTIME: python3.13
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 twilio
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Create deployment package
      working-directory: ./aws/lambda
      run: |
        mkdir -p package
        pip install --target ./package boto3 twilio
        cp AIponATimeCustomerCare.py package/
        cd package
        zip -r ../${{ env.LAMBDA_FUNCTION }}.zip .
        
    - name: Deploy to Lambda
      working-directory: ./aws
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION }} \
          --zip-file fileb://lambda/${{ env.LAMBDA_FUNCTION }}.zip \
          --region ${{ env.AWS_REGION }}
